### ISSUE TITLE
Consider to add this useful git command

### ISSUE THREAD

**Issue by c0510gy** [kmu-sensorcloud/Git-Basic#1]
The `git stash` command is so useful when collaborating with other developers!

It basically stores uncommitted changes to the stack and then erases all the changes so you can do other things and then re-apply the changes you made before by restoring them from the stack using `git stash apply` command.

**Comment by seiwonpark** [comment]
@c0510gy OMG Thank you for commenting :) And your recommendation as well! I'll update that right away.

**Comment by c0510gy** [comment]
LGTM!!
